version: '3.8'

services:
  db:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - /home/stas/db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - default

  bot:
    build: .
    volumes:
      - /home/stas/bot_logs:/app/logs
    depends_on:
      - db
    restart: unless-stopped
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - default
    ports:
      - "8000:8000"
#
#
networks:
  default:
    driver: bridge
